require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set

map("n", ";", ":", { desc = "CMD enter command mode" })
map("i", "jk", "<ESC>")

-- map({ "n", "i", "v" }, "<C-s>", "<cmd> w <cr>")
map("n", "й", "q")
map("n", "ц", "w")
map("n", "у", "e")
map("n", "к", "r")
map("n", "е", "t")
map("n", "н", "y")
map("n", "г", "u")
map("n", "ш", "i")
map("n", "щ", "o")
map("n", "з", "p")
map("n", "х", "[")
map("n", "ъ", "]")
map("n", "ф", "a")
map("n", "ы", "s")
map("n", "в", "d")
map("n", "а", "f")
map("n", "п", "g")
map("n", "р", "h")
map("n", "о", "j")
map("n", "л", "k")
map("n", "д", "l")
map("n", "ж", ";")
map("n", "э", "'")
map("n", "я", "z")
map("n", "ч", "x")
map("n", "с", "c")
map("n", "м", "v")
map("n", "и", "b")
map("n", "т", "n")
map("n", "ь", "m")
map("n", "б", ",")
map("n", "ю", ".")
map("n", "Й", "Q")
map("n", "Ц", "W")
map("n", "У", "E")
map("n", "К", "R")
map("n", "Е", "T")
map("n", "Н", "Y")
map("n", "Г", "U")
map("n", "Ш", "I")
map("n", "Щ", "O")
map("n", "З", "P")
map("n", "Х", "[")
map("n", "Ъ", "]")
map("n", "Ф", "A")
map("n", "Ы", "S")
map("n", "В", "D")
map("n", "А", "F")
map("n", "П", "G")
map("n", "Р", "H")
map("n", "О", "J")
map("n", "Л", "K")
map("n", "Д", "L")
map("n", "Ж", ":")
map("n", "Э", "'")
map("n", "Я", "Z")
map("n", "Ч", "X")
map("n", "С", "C")
map("n", "М", "V")
map("n", "И", "B")
map("n", "Т", "N")
map("n", "Ь", "M")
map("n", "Б", "<")
map("n", "Ю", ">")
